In [11]:
import numpy as np
import networkx as nx

G = nx.Graph()

# dt = {
#     0: "s",
#     1: "a",
#     2: "b",
#     3: "c",
#     4: "t",
#     5: "d",
#     6: "e",
#     7: "f"
# }

# edges = [
#     (0, 1),
#     (1, 2),
#     (2, 3),
#     (3, 0),
#     (4, 5),
#     (5, 6),
#     (6, 7),
#     (7, 4),
#     (0, 4),
#     (1, 5),
#     (2, 6),
#     (3, 7)
# ]

dt = {
    0: "s",
    1: "a",
    2: "c",
    3: "f"
}


edges = [
    (0, 1, {"weight":1}),
    (0, 2, {"weight":2}),
    (1, 2, {"weight":4/3}),
    (1, 3, {"weight":1}),
    (2, 3, {"weight":2})
]


G.add_edges_from(edges)

In [12]:
L = nx.laplacian_matrix(G).todense()
L_inv = np.linalg.pinv(L)

In [13]:
L

matrix([[ 3.        , -1.        , -2.        ,  0.        ],
        [-1.        ,  3.33333333, -1.33333333, -1.        ],
        [-2.        , -1.33333333,  5.33333333, -2.        ],
        [ 0.        , -1.        , -2.        ,  3.        ]])

In [14]:
np.round(L_inv, 2)

array([[ 0.21, -0.06, -0.03, -0.12],
       [-0.06,  0.17, -0.05, -0.06],
       [-0.03, -0.05,  0.11, -0.03],
       [-0.12, -0.06, -0.03,  0.21]])

In [15]:
e_s = np.zeros(len(dt))
e_s[0] = 1

e_t = np.zeros(len(dt))
e_t[3] = 1

diff = e_s - e_t
diff.dot(L_inv.dot(diff).T)

matrix([[0.66666667]])

In [16]:
29/46

0.6304347826086957

In [17]:
22/39

0.5641025641025641